export const LOAD_COURSE_CLASS = 'CourseClass/LOAD_COURSE_CLASS';
export const LOAD_COURSE_CLASS_SUCCESS =
  'CourseClass/LOAD_COURSE_CLASS_SUCCESS';
export const LOAD_COURSE_CLASS_ERROR = 'CourseClass/LOAD_COURSE_CLASS_ERROR';
