<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "Mark".
 *
 * @property integer $ID
 * @property integer $Student_Class_ID
 * @property integer $Task_ID
 * @property string $Value
 * @property integer $Approved
 *
 * @property \app\models\StudentClass $studentClass
 * @property \app\models\Task $task
 * @property string $aliasModel
 */
abstract class Mark extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Mark';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Student_Class_ID', 'Task_ID', 'Value', 'Approved'], 'required'],
            [['Student_Class_ID', 'Task_ID', 'Approved'], 'integer'],
            [['Value'], 'number'],
            [['Student_Class_ID'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\StudentClass::className(), 'targetAttribute' => ['Student_Class_ID' => 'ID']],
            [['Task_ID'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Task::className(), 'targetAttribute' => ['Task_ID' => 'ID']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'Student_Class_ID' => 'Student  Class  ID',
            'Task_ID' => 'Task  ID',
            'Value' => 'Value',
            'Approved' => 'Approved',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentClass()
    {
        return $this->hasOne(\app\models\StudentClass::className(), ['ID' => 'Student_Class_ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTask()
    {
        return $this->hasOne(\app\models\Task::className(), ['ID' => 'Task_ID']);
    }




}
