<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "Student_Class".
 *
 * @property integer $ID
 * @property integer $Student_ID
 * @property integer $Class_ID
 *
 * @property \app\models\Mark[] $marks
 * @property \app\models\Class $class
 * @property \app\models\Student $student
 * @property string $aliasModel
 */
abstract class StudentClass extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Student_Class';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Student_ID', 'Class_ID'], 'required'],
            [['Student_ID', 'Class_ID'], 'integer'],
            [['Class_ID'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CourseClass::className(), 'targetAttribute' => ['Class_ID' => 'ID']],
            [['Student_ID'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Student::className(), 'targetAttribute' => ['Student_ID' => 'ID']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'Student_ID' => 'Student  ID',
            'Class_ID' => 'Class  ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMarks()
    {
        return $this->hasMany(\app\models\Mark::className(), ['Student_Class_ID' => 'ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClass()
    {
        return $this->hasOne(\app\models\CourseClass::className(), ['ID' => 'Class_ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(\app\models\Student::className(), ['ID' => 'Student_ID']);
    }




}
