<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "Subject_SubjectGroup".
 *
 * @property integer $Subject_ID
 * @property integer $SubjectGroup_ID
 *
 * @property \app\models\Subject $subject
 * @property \app\models\SubjectGroup $subjectGroup
 * @property string $aliasModel
 */
abstract class SubjectSubjectGroup extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Subject_SubjectGroup';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Subject_ID', 'SubjectGroup_ID'], 'required'],
            [['Subject_ID', 'SubjectGroup_ID'], 'integer'],
            [['Subject_ID', 'SubjectGroup_ID'], 'unique', 'targetAttribute' => ['Subject_ID', 'SubjectGroup_ID']],
            [['Subject_ID'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Subject::className(), 'targetAttribute' => ['Subject_ID' => 'ID']],
            [['SubjectGroup_ID'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\SubjectGroup::className(), 'targetAttribute' => ['SubjectGroup_ID' => 'ID']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'Subject_ID' => 'Subject  ID',
            'SubjectGroup_ID' => 'Subject Group  ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubject()
    {
        return $this->hasOne(\app\models\Subject::className(), ['ID' => 'Subject_ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubjectGroup()
    {
        return $this->hasOne(\app\models\SubjectGroup::className(), ['ID' => 'SubjectGroup_ID']);
    }




}
