<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "Task".
 *
 * @property integer $ID
 * @property string $Name
 * @property string $MarkWeightAverage
 * @property string $TotalMark
 * @property integer $TeacherClass_ID
 * @property integer $TaskCategory_ID
 *
 * @property \app\models\Mark[] $marks
 * @property \app\models\TeacherClass $teacherClass
 * @property \app\models\TaskCategory $taskCategory
 * @property string $aliasModel
 */
abstract class Task extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Task';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Name', 'MarkWeightAverage', 'TotalMark', 'TeacherClass_ID', 'TaskCategory_ID'], 'required'],
            [['MarkWeightAverage', 'TotalMark'], 'number'],
            [['TeacherClass_ID', 'TaskCategory_ID'], 'integer'],
            [['Name'], 'string', 'max' => 155],
            [['TeacherClass_ID'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TeacherClass::className(), 'targetAttribute' => ['TeacherClass_ID' => 'ID']],
            [['TaskCategory_ID'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TaskCategory::className(), 'targetAttribute' => ['TaskCategory_ID' => 'ID']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'Name' => 'Name',
            'MarkWeightAverage' => 'Mark Weight Average',
            'TotalMark' => 'Total Mark',
            'TeacherClass_ID' => 'Teacher Class  ID',
            'TaskCategory_ID' => 'Task Category  ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMarks()
    {
        return $this->hasMany(\app\models\Mark::className(), ['Task_ID' => 'ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTeacherClass()
    {
        return $this->hasOne(\app\models\TeacherClass::className(), ['ID' => 'TeacherClass_ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTaskCategory()
    {
        return $this->hasOne(\app\models\TaskCategory::className(), ['ID' => 'TaskCategory_ID']);
    }




}
