<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "Teacher".
 *
 * @property integer $ID
 * @property integer $User_ID
 *
 * @property \app\models\User $user
 * @property \app\models\TeacherClass[] $teacherClasses
 * @property \app\models\Class[] $classes
 * @property \app\models\TeacherSubject[] $teacherSubjects
 * @property \app\models\Subject[] $subjects
 * @property string $aliasModel
 */
abstract class Teacher extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Teacher';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['User_ID'], 'required'],
            [['User_ID'], 'integer'],
            [['User_ID'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['User_ID' => 'ID']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'User_ID' => 'User  ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['ID' => 'User_ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTeacherClasses()
    {
        return $this->hasMany(\app\models\TeacherClass::className(), ['Teacher_ID' => 'ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClasses()
    {
        return $this->hasMany(\app\models\CourseClass::className(), ['ID' => 'Class_ID'])->viaTable('Teacher_Class', ['Teacher_ID' => 'ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTeacherSubjects()
    {
        return $this->hasMany(\app\models\TeacherSubject::className(), ['Teacher_ID' => 'ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubjects()
    {
        return $this->hasMany(\app\models\Subject::className(), ['ID' => 'Subject_ID'])->viaTable('Teacher_Subject', ['Teacher_ID' => 'ID']);
    }




}
