<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "Teacher_Class".
 *
 * @property integer $ID
 * @property integer $Teacher_ID
 * @property integer $Class_ID
 * @property integer $Subject_ID
 *
 * @property \app\models\Task[] $tasks
 * @property \app\models\Class $class
 * @property string $aliasModel
 */
abstract class TeacherClass extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Teacher_Class';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ID', 'Teacher_ID', 'Class_ID', 'Subject_ID'], 'required'],
            [['ID', 'Teacher_ID', 'Class_ID', 'Subject_ID'], 'integer'],
            [['ID'], 'unique'],
            [['Class_ID'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CourseClass::className(), 'targetAttribute' => ['Class_ID' => 'ID']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ID' => 'ID',
            'Teacher_ID' => 'Teacher  ID',
            'Class_ID' => 'Class  ID',
            'Subject_ID' => 'Subject  ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTasks()
    {
        return $this->hasMany(\app\models\Task::className(), ['TeacherClass_ID' => 'ID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClass()
    {
        return $this->hasOne(\app\models\CourseClass::className(), ['ID' => 'Class_ID']);
    }




}
